[variables]
NIXPACKS_NODE_PACKAGE_MANAGER = "pnpm"
PNPM_HOME = "/root/.local/share/pnpm"

[phases.install]
cmds = ["pnpm install --prod=false --no-frozen-lockfile"]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "pnpm run start"
