export const dynamic = 'force-dynamic'
import { NextResponse } from 'next/server'
import { connectMongo } from '@/lib/db'
import { isResponse, requireDashboardSession } from '@/lib/api-helpers'
import { apiError, withErrors } from '@/lib/errors'
import { decryptSipPassword } from '@/lib/sip'
import { PhoneNumber } from '@/models/PhoneNumber'

type FreeswitchNumber = {
  e164: string
  providerSlug?: string
  sipServer?: string
  sipPort?: number
  sipProxy?: string
  sipRealm?: string
  sipUsername?: string
  sipAuthUsername?: string
  sipPassword?: string
  sipRegister?: boolean
  sipTransport?: 'udp' | 'tcp' | 'tls'
  sipCodecs?: string
}

function xmlAttr(value: unknown): string {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/"/g, '&quot;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
}

function gatewayHostPort(host: string, port?: number): string {
  const clean = host.trim()
  if (!clean || !port || clean.includes(':')) return clean
  return `${clean}:${port}`
}

function fsCodecPrefs(value?: string): string {
  return (value || 'PCMU@20i').replace(/@(\d+)ms\b/g, '@$1i')
}

function renderGatewayXml(numbers: FreeswitchNumber[]): string {
  const bySlug = new Map<string, FreeswitchNumber>()
  const skipped: string[] = []
  for (const n of numbers) {
    const slug = (n.providerSlug || '').trim()
    if (!slug || !n.sipServer || !n.sipUsername) continue
    if (bySlug.has(slug)) {
      skipped.push(`${slug}:${n.e164}`)
      continue
    }
    bySlug.set(slug, n)
  }
  const gateways = [...bySlug.values()]
    .map((n) => {
      const slug = n.providerSlug || 'sip_custom'
      const proxy = gatewayHostPort(n.sipProxy || n.sipServer || '', n.sipPort)
      const realm = n.sipRealm || n.sipServer || proxy
      const password = decryptSipPassword(n.sipPassword || '')
      return `  <gateway name="${xmlAttr(slug)}">
    <param name="username" value="${xmlAttr(n.sipUsername)}"/>
    <param name="auth-username" value="${xmlAttr(n.sipAuthUsername || n.sipUsername)}"/>
    <param name="password" value="${xmlAttr(password)}"/>
    <param name="realm" value="${xmlAttr(realm)}"/>
    <param name="proxy" value="${xmlAttr(proxy)}"/>
    <param name="register-proxy" value="${xmlAttr(proxy)}"/>
    <param name="register" value="${n.sipRegister === false ? 'false' : 'true'}"/>
    <param name="transport" value="${xmlAttr(n.sipTransport || 'udp')}"/>
    <param name="caller-id-in-from" value="true"/>
    <param name="codec-prefs" value="${xmlAttr(fsCodecPrefs(n.sipCodecs))}"/>
  </gateway>`
    })
    .join('\n')
  const comments = skipped.length
    ? `\n  <!-- skipped duplicate providerSlug rows: ${xmlAttr(skipped.join(', '))} -->`
    : ''
  return `<include>
  <!-- generated by LivoCall /api/numbers/freeswitch -->${comments}
${gateways}
</include>
`
}

function hasConfigToken(req: Request): boolean {
  const token = process.env.FREESWITCH_CONFIG_TOKEN || ''
  const auth = req.headers.get('authorization') || ''
  return Boolean(token && auth === `Bearer ${token}`)
}

export const GET = withErrors(async (req: Request) => {
  const url = new URL(req.url)
  if (url.searchParams.get('format') === 'xml' || hasConfigToken(req)) {
    if (!hasConfigToken(req)) return apiError('unauthenticated')
    const orgId = req.headers.get('x-livocall-org-id') || url.searchParams.get('orgId') || ''
    await connectMongo()
    const numbers = await PhoneNumber.find({
      ...(orgId ? { orgId } : {}),
      status: 'active',
      outboundEnabled: true,
      sipServer: { $ne: '' },
      sipUsername: { $ne: '' },
    })
      .select('+sipPassword')
      .sort({ providerSlug: 1, e164: 1 })
      .lean<FreeswitchNumber[]>()
    return new Response(renderGatewayXml(numbers), {
      headers: {
        'content-type': 'application/xml; charset=utf-8',
        'cache-control': 'no-store',
      },
    })
  }

  const s = await requireDashboardSession()
  if (isResponse(s)) return s
  await connectMongo()
  const numbers = await PhoneNumber.find({ orgId: s.orgId, inboundEnabled: true })
    .sort({ e164: 1 })
    .lean()
  return NextResponse.json({
    numbers: numbers.map((n) => ({
      e164: n.e164,
      sipServer: n.sipServer,
      sipUsername: n.sipUsername,
      agentId: n.agentId ? String(n.agentId) : null,
    })),
  })
})
